/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOraclePegFacet {
  export type PegConfigStruct = {
    oracleAddress: AddressLike;
    twapPeriod: BigNumberish;
    maxStaleness: BigNumberish;
    maxSpotDeviation: BigNumberish;
  };

  export type PegConfigStructOutput = [
    oracleAddress: string,
    twapPeriod: bigint,
    maxStaleness: bigint,
    maxSpotDeviation: bigint
  ] & {
    oracleAddress: string;
    twapPeriod: bigint;
    maxStaleness: bigint;
    maxSpotDeviation: bigint;
  };
}

export interface IOraclePegFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getOracleMidPrice"
      | "getPegConfig"
      | "removeOraclePeg"
      | "setOraclePeg"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CircuitBreakerTriggered"
      | "OraclePegRemoved"
      | "OraclePegSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getOracleMidPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPegConfig",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOraclePeg",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOraclePeg",
    values: [BytesLike, IOraclePegFacet.PegConfigStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getOracleMidPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPegConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOraclePeg",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOraclePeg",
    data: BytesLike
  ): Result;
}

export namespace CircuitBreakerTriggeredEvent {
  export type InputTuple = [poolId: BytesLike, reason: string];
  export type OutputTuple = [poolId: string, reason: string];
  export interface OutputObject {
    poolId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OraclePegRemovedEvent {
  export type InputTuple = [poolId: BytesLike];
  export type OutputTuple = [poolId: string];
  export interface OutputObject {
    poolId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OraclePegSetEvent {
  export type InputTuple = [
    poolId: BytesLike,
    oracle: AddressLike,
    twapPeriod: BigNumberish,
    maxStaleness: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    oracle: string,
    twapPeriod: bigint,
    maxStaleness: bigint
  ];
  export interface OutputObject {
    poolId: string;
    oracle: string;
    twapPeriod: bigint;
    maxStaleness: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IOraclePegFacet extends BaseContract {
  connect(runner?: ContractRunner | null): IOraclePegFacet;
  waitForDeployment(): Promise<this>;

  interface: IOraclePegFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getOracleMidPrice: TypedContractMethod<
    [poolId: BytesLike],
    [[bigint, boolean] & { midPrice: bigint; isValid: boolean }],
    "view"
  >;

  getPegConfig: TypedContractMethod<
    [poolId: BytesLike],
    [IOraclePegFacet.PegConfigStructOutput],
    "view"
  >;

  removeOraclePeg: TypedContractMethod<
    [poolId: BytesLike],
    [void],
    "nonpayable"
  >;

  setOraclePeg: TypedContractMethod<
    [poolId: BytesLike, config: IOraclePegFacet.PegConfigStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getOracleMidPrice"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [[bigint, boolean] & { midPrice: bigint; isValid: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPegConfig"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [IOraclePegFacet.PegConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeOraclePeg"
  ): TypedContractMethod<[poolId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOraclePeg"
  ): TypedContractMethod<
    [poolId: BytesLike, config: IOraclePegFacet.PegConfigStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CircuitBreakerTriggered"
  ): TypedContractEvent<
    CircuitBreakerTriggeredEvent.InputTuple,
    CircuitBreakerTriggeredEvent.OutputTuple,
    CircuitBreakerTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "OraclePegRemoved"
  ): TypedContractEvent<
    OraclePegRemovedEvent.InputTuple,
    OraclePegRemovedEvent.OutputTuple,
    OraclePegRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OraclePegSet"
  ): TypedContractEvent<
    OraclePegSetEvent.InputTuple,
    OraclePegSetEvent.OutputTuple,
    OraclePegSetEvent.OutputObject
  >;

  filters: {
    "CircuitBreakerTriggered(bytes32,string)": TypedContractEvent<
      CircuitBreakerTriggeredEvent.InputTuple,
      CircuitBreakerTriggeredEvent.OutputTuple,
      CircuitBreakerTriggeredEvent.OutputObject
    >;
    CircuitBreakerTriggered: TypedContractEvent<
      CircuitBreakerTriggeredEvent.InputTuple,
      CircuitBreakerTriggeredEvent.OutputTuple,
      CircuitBreakerTriggeredEvent.OutputObject
    >;

    "OraclePegRemoved(bytes32)": TypedContractEvent<
      OraclePegRemovedEvent.InputTuple,
      OraclePegRemovedEvent.OutputTuple,
      OraclePegRemovedEvent.OutputObject
    >;
    OraclePegRemoved: TypedContractEvent<
      OraclePegRemovedEvent.InputTuple,
      OraclePegRemovedEvent.OutputTuple,
      OraclePegRemovedEvent.OutputObject
    >;

    "OraclePegSet(bytes32,address,uint32,uint32)": TypedContractEvent<
      OraclePegSetEvent.InputTuple,
      OraclePegSetEvent.OutputTuple,
      OraclePegSetEvent.OutputObject
    >;
    OraclePegSet: TypedContractEvent<
      OraclePegSetEvent.InputTuple,
      OraclePegSetEvent.OutputTuple,
      OraclePegSetEvent.OutputObject
    >;
  };
}
