/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IRewardFacet {
  export type LPRewardInfoStruct = {
    loyaltyMultiplier: BigNumberish;
    accumulatedFees0: BigNumberish;
    accumulatedFees1: BigNumberish;
    depositTimestamp: BigNumberish;
    cumulativeVolume: BigNumberish;
  };

  export type LPRewardInfoStructOutput = [
    loyaltyMultiplier: bigint,
    accumulatedFees0: bigint,
    accumulatedFees1: bigint,
    depositTimestamp: bigint,
    cumulativeVolume: bigint
  ] & {
    loyaltyMultiplier: bigint;
    accumulatedFees0: bigint;
    accumulatedFees1: bigint;
    depositTimestamp: bigint;
    cumulativeVolume: bigint;
  };

  export type TraderRewardInfoStruct = {
    currentEpoch: BigNumberish;
    epochSwapCount: BigNumberish;
    epochVolume: BigNumberish;
    pendingRebate0: BigNumberish;
    pendingRebate1: BigNumberish;
  };

  export type TraderRewardInfoStructOutput = [
    currentEpoch: bigint,
    epochSwapCount: bigint,
    epochVolume: bigint,
    pendingRebate0: bigint,
    pendingRebate1: bigint
  ] & {
    currentEpoch: bigint;
    epochSwapCount: bigint;
    epochVolume: bigint;
    pendingRebate0: bigint;
    pendingRebate1: bigint;
  };

  export type EpochConfigStruct = {
    epochDuration: BigNumberish;
    minSwapsForRebate: BigNumberish;
    maxTradeSize: BigNumberish;
  };

  export type EpochConfigStructOutput = [
    epochDuration: bigint,
    minSwapsForRebate: bigint,
    maxTradeSize: bigint
  ] & {
    epochDuration: bigint;
    minSwapsForRebate: bigint;
    maxTradeSize: bigint;
  };
}

export interface IRewardFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "advanceEpoch"
      | "claimTraderRebate"
      | "getCurrentEpoch"
      | "getLPMultiplier"
      | "getLPRewardInfo"
      | "getTraderRewardInfo"
      | "setEpochConfig"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EpochAdvanced"
      | "LPRewardsClaimed"
      | "TraderRebateClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "advanceEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimTraderRebate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLPMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLPRewardInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTraderRewardInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEpochConfig",
    values: [IRewardFacet.EpochConfigStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "advanceEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTraderRebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLPMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLPRewardInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraderRewardInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEpochConfig",
    data: BytesLike
  ): Result;
}

export namespace EpochAdvancedEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    totalRebatePool0: BigNumberish,
    totalRebatePool1: BigNumberish
  ];
  export type OutputTuple = [
    epoch: bigint,
    totalRebatePool0: bigint,
    totalRebatePool1: bigint
  ];
  export interface OutputObject {
    epoch: bigint;
    totalRebatePool0: bigint;
    totalRebatePool1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPRewardsClaimedEvent {
  export type InputTuple = [
    lp: AddressLike,
    positionId: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    lp: string,
    positionId: bigint,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    lp: string;
    positionId: bigint;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TraderRebateClaimedEvent {
  export type InputTuple = [
    trader: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [trader: string, amount0: bigint, amount1: bigint];
  export interface OutputObject {
    trader: string;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRewardFacet extends BaseContract {
  connect(runner?: ContractRunner | null): IRewardFacet;
  waitForDeployment(): Promise<this>;

  interface: IRewardFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  advanceEpoch: TypedContractMethod<[], [void], "nonpayable">;

  claimTraderRebate: TypedContractMethod<
    [recipient: AddressLike],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;

  getCurrentEpoch: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        epoch: bigint;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;

  getLPMultiplier: TypedContractMethod<
    [positionId: BigNumberish],
    [bigint],
    "view"
  >;

  getLPRewardInfo: TypedContractMethod<
    [positionId: BigNumberish],
    [IRewardFacet.LPRewardInfoStructOutput],
    "view"
  >;

  getTraderRewardInfo: TypedContractMethod<
    [trader: AddressLike],
    [IRewardFacet.TraderRewardInfoStructOutput],
    "view"
  >;

  setEpochConfig: TypedContractMethod<
    [config: IRewardFacet.EpochConfigStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "advanceEpoch"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTraderRebate"
  ): TypedContractMethod<
    [recipient: AddressLike],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCurrentEpoch"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        epoch: bigint;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLPMultiplier"
  ): TypedContractMethod<[positionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLPRewardInfo"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [IRewardFacet.LPRewardInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTraderRewardInfo"
  ): TypedContractMethod<
    [trader: AddressLike],
    [IRewardFacet.TraderRewardInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "setEpochConfig"
  ): TypedContractMethod<
    [config: IRewardFacet.EpochConfigStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EpochAdvanced"
  ): TypedContractEvent<
    EpochAdvancedEvent.InputTuple,
    EpochAdvancedEvent.OutputTuple,
    EpochAdvancedEvent.OutputObject
  >;
  getEvent(
    key: "LPRewardsClaimed"
  ): TypedContractEvent<
    LPRewardsClaimedEvent.InputTuple,
    LPRewardsClaimedEvent.OutputTuple,
    LPRewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TraderRebateClaimed"
  ): TypedContractEvent<
    TraderRebateClaimedEvent.InputTuple,
    TraderRebateClaimedEvent.OutputTuple,
    TraderRebateClaimedEvent.OutputObject
  >;

  filters: {
    "EpochAdvanced(uint256,uint256,uint256)": TypedContractEvent<
      EpochAdvancedEvent.InputTuple,
      EpochAdvancedEvent.OutputTuple,
      EpochAdvancedEvent.OutputObject
    >;
    EpochAdvanced: TypedContractEvent<
      EpochAdvancedEvent.InputTuple,
      EpochAdvancedEvent.OutputTuple,
      EpochAdvancedEvent.OutputObject
    >;

    "LPRewardsClaimed(address,uint256,uint256,uint256)": TypedContractEvent<
      LPRewardsClaimedEvent.InputTuple,
      LPRewardsClaimedEvent.OutputTuple,
      LPRewardsClaimedEvent.OutputObject
    >;
    LPRewardsClaimed: TypedContractEvent<
      LPRewardsClaimedEvent.InputTuple,
      LPRewardsClaimedEvent.OutputTuple,
      LPRewardsClaimedEvent.OutputObject
    >;

    "TraderRebateClaimed(address,uint256,uint256)": TypedContractEvent<
      TraderRebateClaimedEvent.InputTuple,
      TraderRebateClaimedEvent.OutputTuple,
      TraderRebateClaimedEvent.OutputObject
    >;
    TraderRebateClaimed: TypedContractEvent<
      TraderRebateClaimedEvent.InputTuple,
      TraderRebateClaimedEvent.OutputTuple,
      TraderRebateClaimedEvent.OutputObject
    >;
  };
}
