/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FixedPointMathTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "Q128"
      | "divQ128"
      | "fromQ128"
      | "mulQ128"
      | "sqrt"
      | "sqrtQ128"
      | "tanh"
      | "toQ128"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "Q128", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "divQ128",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fromQ128",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mulQ128",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sqrt", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "sqrtQ128",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tanh", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "toQ128",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "Q128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "divQ128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fromQ128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mulQ128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sqrt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sqrtQ128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tanh", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toQ128", data: BytesLike): Result;
}

export interface FixedPointMathTest extends BaseContract {
  connect(runner?: ContractRunner | null): FixedPointMathTest;
  waitForDeployment(): Promise<this>;

  interface: FixedPointMathTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  Q128: TypedContractMethod<[], [bigint], "view">;

  divQ128: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "view"
  >;

  fromQ128: TypedContractMethod<[x: BigNumberish], [bigint], "view">;

  mulQ128: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "view"
  >;

  sqrt: TypedContractMethod<[x: BigNumberish], [bigint], "view">;

  sqrtQ128: TypedContractMethod<[x: BigNumberish], [bigint], "view">;

  tanh: TypedContractMethod<[x: BigNumberish], [bigint], "view">;

  toQ128: TypedContractMethod<[x: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "Q128"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "divQ128"
  ): TypedContractMethod<[a: BigNumberish, b: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "fromQ128"
  ): TypedContractMethod<[x: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "mulQ128"
  ): TypedContractMethod<[a: BigNumberish, b: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "sqrt"
  ): TypedContractMethod<[x: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "sqrtQ128"
  ): TypedContractMethod<[x: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tanh"
  ): TypedContractMethod<[x: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "toQ128"
  ): TypedContractMethod<[x: BigNumberish], [bigint], "view">;

  filters: {};
}
