/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IFeeFacet {
  export type FeeConfigStruct = {
    baseFee: BigNumberish;
    maxImpactFee: BigNumberish;
    lpShareBps: BigNumberish;
    protocolShareBps: BigNumberish;
    traderShareBps: BigNumberish;
  };

  export type FeeConfigStructOutput = [
    baseFee: bigint,
    maxImpactFee: bigint,
    lpShareBps: bigint,
    protocolShareBps: bigint,
    traderShareBps: bigint
  ] & {
    baseFee: bigint;
    maxImpactFee: bigint;
    lpShareBps: bigint;
    protocolShareBps: bigint;
    traderShareBps: bigint;
  };
}

export interface LibFeeTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyFee"
      | "calculateProgressiveFee"
      | "defaultFeeConfig"
      | "distributeFee"
      | "validateFeeConfig"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "applyFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateProgressiveFee",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultFeeConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeFee",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateFeeConfig",
    values: [IFeeFacet.FeeConfigStruct]
  ): string;

  decodeFunctionResult(functionFragment: "applyFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateProgressiveFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateFeeConfig",
    data: BytesLike
  ): Result;
}

export interface LibFeeTest extends BaseContract {
  connect(runner?: ContractRunner | null): LibFeeTest;
  waitForDeployment(): Promise<this>;

  interface: LibFeeTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyFee: TypedContractMethod<
    [amount: BigNumberish, feeBps: BigNumberish],
    [[bigint, bigint] & { netAmount: bigint; feeAmount: bigint }],
    "view"
  >;

  calculateProgressiveFee: TypedContractMethod<
    [
      baseFee: BigNumberish,
      maxImpactFee: BigNumberish,
      tradeSize: BigNumberish,
      poolLiquidity: BigNumberish
    ],
    [bigint],
    "view"
  >;

  defaultFeeConfig: TypedContractMethod<
    [],
    [IFeeFacet.FeeConfigStructOutput],
    "view"
  >;

  distributeFee: TypedContractMethod<
    [
      totalFee: BigNumberish,
      lpShareBps: BigNumberish,
      protocolShareBps: BigNumberish,
      traderShareBps: BigNumberish
    ],
    [
      [bigint, bigint, bigint] & {
        lpFee: bigint;
        protocolFee: bigint;
        traderFee: bigint;
      }
    ],
    "view"
  >;

  validateFeeConfig: TypedContractMethod<
    [config: IFeeFacet.FeeConfigStruct],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyFee"
  ): TypedContractMethod<
    [amount: BigNumberish, feeBps: BigNumberish],
    [[bigint, bigint] & { netAmount: bigint; feeAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateProgressiveFee"
  ): TypedContractMethod<
    [
      baseFee: BigNumberish,
      maxImpactFee: BigNumberish,
      tradeSize: BigNumberish,
      poolLiquidity: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "defaultFeeConfig"
  ): TypedContractMethod<[], [IFeeFacet.FeeConfigStructOutput], "view">;
  getFunction(
    nameOrSignature: "distributeFee"
  ): TypedContractMethod<
    [
      totalFee: BigNumberish,
      lpShareBps: BigNumberish,
      protocolShareBps: BigNumberish,
      traderShareBps: BigNumberish
    ],
    [
      [bigint, bigint, bigint] & {
        lpFee: bigint;
        protocolFee: bigint;
        traderFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateFeeConfig"
  ): TypedContractMethod<[config: IFeeFacet.FeeConfigStruct], [void], "view">;

  filters: {};
}
