/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface OracleFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "consultTWAP"
      | "getOracleState"
      | "getSpotTick"
      | "increaseObservationCardinalityNext"
      | "observe"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ObservationRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "consultTWAP",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpotTick",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseObservationCardinalityNext",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "observe",
    values: [BytesLike, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "consultTWAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOracleState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpotTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseObservationCardinalityNext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "observe", data: BytesLike): Result;
}

export namespace ObservationRecordedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    timestamp: BigNumberish,
    tick: BigNumberish,
    liquidity: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    timestamp: bigint,
    tick: bigint,
    liquidity: bigint
  ];
  export interface OutputObject {
    poolId: string;
    timestamp: bigint;
    tick: bigint;
    liquidity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleFacet extends BaseContract {
  connect(runner?: ContractRunner | null): OracleFacet;
  waitForDeployment(): Promise<this>;

  interface: OracleFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consultTWAP: TypedContractMethod<
    [poolId: BytesLike, period: BigNumberish],
    [bigint],
    "view"
  >;

  getOracleState: TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        index: bigint;
        cardinality: bigint;
        cardinalityNext: bigint;
      }
    ],
    "view"
  >;

  getSpotTick: TypedContractMethod<[poolId: BytesLike], [bigint], "view">;

  increaseObservationCardinalityNext: TypedContractMethod<
    [poolId: BytesLike, observationCardinalityNext: BigNumberish],
    [void],
    "nonpayable"
  >;

  observe: TypedContractMethod<
    [poolId: BytesLike, secondsAgos: BigNumberish[]],
    [bigint[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consultTWAP"
  ): TypedContractMethod<
    [poolId: BytesLike, period: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOracleState"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        index: bigint;
        cardinality: bigint;
        cardinalityNext: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSpotTick"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "increaseObservationCardinalityNext"
  ): TypedContractMethod<
    [poolId: BytesLike, observationCardinalityNext: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "observe"
  ): TypedContractMethod<
    [poolId: BytesLike, secondsAgos: BigNumberish[]],
    [bigint[]],
    "view"
  >;

  getEvent(
    key: "ObservationRecorded"
  ): TypedContractEvent<
    ObservationRecordedEvent.InputTuple,
    ObservationRecordedEvent.OutputTuple,
    ObservationRecordedEvent.OutputObject
  >;

  filters: {
    "ObservationRecorded(bytes32,uint32,int24,uint128)": TypedContractEvent<
      ObservationRecordedEvent.InputTuple,
      ObservationRecordedEvent.OutputTuple,
      ObservationRecordedEvent.OutputObject
    >;
    ObservationRecorded: TypedContractEvent<
      ObservationRecordedEvent.InputTuple,
      ObservationRecordedEvent.OutputTuple,
      ObservationRecordedEvent.OutputObject
    >;
  };
}
