/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOrderFacet {
  export type OrderStruct = {
    orderId: BigNumberish;
    poolId: BytesLike;
    owner: AddressLike;
    orderType: BigNumberish;
    zeroForOne: boolean;
    targetTick: BigNumberish;
    amountTotal: BigNumberish;
    amountFilled: BigNumberish;
    depositTimestamp: BigNumberish;
    expiry: BigNumberish;
    status: BigNumberish;
  };

  export type OrderStructOutput = [
    orderId: bigint,
    poolId: string,
    owner: string,
    orderType: bigint,
    zeroForOne: boolean,
    targetTick: bigint,
    amountTotal: bigint,
    amountFilled: bigint,
    depositTimestamp: bigint,
    expiry: bigint,
    status: bigint
  ] & {
    orderId: bigint;
    poolId: string;
    owner: string;
    orderType: bigint;
    zeroForOne: boolean;
    targetTick: bigint;
    amountTotal: bigint;
    amountFilled: bigint;
    depositTimestamp: bigint;
    expiry: bigint;
    status: bigint;
  };

  export type PlaceOrderParamsStruct = {
    poolId: BytesLike;
    orderType: BigNumberish;
    zeroForOne: boolean;
    targetTick: BigNumberish;
    amount: BigNumberish;
    expiry: BigNumberish;
  };

  export type PlaceOrderParamsStructOutput = [
    poolId: string,
    orderType: bigint,
    zeroForOne: boolean,
    targetTick: bigint,
    amount: bigint,
    expiry: bigint
  ] & {
    poolId: string;
    orderType: bigint;
    zeroForOne: boolean;
    targetTick: bigint;
    amount: bigint;
    expiry: bigint;
  };
}

export interface OrderFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelOrder"
      | "executeOrder"
      | "expireOrdersAtTick"
      | "getActiveOrderCount"
      | "getOrder"
      | "getOrdersAtTick"
      | "placeOrder"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OrderCancelled"
      | "OrderExecutedByKeeper"
      | "OrderExpired"
      | "OrderFilled"
      | "OrderPartiallyFilled"
      | "OrderPlaced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "expireOrdersAtTick",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOrderCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrdersAtTick",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeOrder",
    values: [IOrderFacet.PlaceOrderParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expireOrdersAtTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrdersAtTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeOrder", data: BytesLike): Result;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderExecutedByKeeperEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    keeper: AddressLike,
    bounty: BigNumberish
  ];
  export type OutputTuple = [orderId: bigint, keeper: string, bounty: bigint];
  export interface OutputObject {
    orderId: bigint;
    keeper: string;
    bounty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderExpiredEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    amountFilled: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    amountFilled: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    amountFilled: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderPartiallyFilledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    amountFilled: BigNumberish,
    remaining: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    amountFilled: bigint,
    remaining: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    amountFilled: bigint;
    remaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderPlacedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    poolId: BytesLike,
    owner: AddressLike,
    orderType: BigNumberish,
    targetTick: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    poolId: string,
    owner: string,
    orderType: bigint,
    targetTick: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    poolId: string;
    owner: string;
    orderType: bigint;
    targetTick: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OrderFacet extends BaseContract {
  connect(runner?: ContractRunner | null): OrderFacet;
  waitForDeployment(): Promise<this>;

  interface: OrderFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [[bigint, bigint] & { amountOut: bigint; bounty: bigint }],
    "nonpayable"
  >;

  expireOrdersAtTick: TypedContractMethod<
    [poolId: BytesLike, tick: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getActiveOrderCount: TypedContractMethod<
    [poolId: BytesLike],
    [bigint],
    "view"
  >;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [IOrderFacet.OrderStructOutput],
    "view"
  >;

  getOrdersAtTick: TypedContractMethod<
    [poolId: BytesLike, tick: BigNumberish],
    [bigint[]],
    "view"
  >;

  placeOrder: TypedContractMethod<
    [params: IOrderFacet.PlaceOrderParamsStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [[bigint, bigint] & { amountOut: bigint; bounty: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "expireOrdersAtTick"
  ): TypedContractMethod<
    [poolId: BytesLike, tick: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveOrderCount"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [IOrderFacet.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrdersAtTick"
  ): TypedContractMethod<
    [poolId: BytesLike, tick: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeOrder"
  ): TypedContractMethod<
    [params: IOrderFacet.PlaceOrderParamsStruct],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderExecutedByKeeper"
  ): TypedContractEvent<
    OrderExecutedByKeeperEvent.InputTuple,
    OrderExecutedByKeeperEvent.OutputTuple,
    OrderExecutedByKeeperEvent.OutputObject
  >;
  getEvent(
    key: "OrderExpired"
  ): TypedContractEvent<
    OrderExpiredEvent.InputTuple,
    OrderExpiredEvent.OutputTuple,
    OrderExpiredEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "OrderPartiallyFilled"
  ): TypedContractEvent<
    OrderPartiallyFilledEvent.InputTuple,
    OrderPartiallyFilledEvent.OutputTuple,
    OrderPartiallyFilledEvent.OutputObject
  >;
  getEvent(
    key: "OrderPlaced"
  ): TypedContractEvent<
    OrderPlacedEvent.InputTuple,
    OrderPlacedEvent.OutputTuple,
    OrderPlacedEvent.OutputObject
  >;

  filters: {
    "OrderCancelled(uint256)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderExecutedByKeeper(uint256,address,uint256)": TypedContractEvent<
      OrderExecutedByKeeperEvent.InputTuple,
      OrderExecutedByKeeperEvent.OutputTuple,
      OrderExecutedByKeeperEvent.OutputObject
    >;
    OrderExecutedByKeeper: TypedContractEvent<
      OrderExecutedByKeeperEvent.InputTuple,
      OrderExecutedByKeeperEvent.OutputTuple,
      OrderExecutedByKeeperEvent.OutputObject
    >;

    "OrderExpired(uint256)": TypedContractEvent<
      OrderExpiredEvent.InputTuple,
      OrderExpiredEvent.OutputTuple,
      OrderExpiredEvent.OutputObject
    >;
    OrderExpired: TypedContractEvent<
      OrderExpiredEvent.InputTuple,
      OrderExpiredEvent.OutputTuple,
      OrderExpiredEvent.OutputObject
    >;

    "OrderFilled(uint256,uint256,uint256)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "OrderPartiallyFilled(uint256,uint256,uint256)": TypedContractEvent<
      OrderPartiallyFilledEvent.InputTuple,
      OrderPartiallyFilledEvent.OutputTuple,
      OrderPartiallyFilledEvent.OutputObject
    >;
    OrderPartiallyFilled: TypedContractEvent<
      OrderPartiallyFilledEvent.InputTuple,
      OrderPartiallyFilledEvent.OutputTuple,
      OrderPartiallyFilledEvent.OutputObject
    >;

    "OrderPlaced(uint256,bytes32,address,uint8,int24,uint256)": TypedContractEvent<
      OrderPlacedEvent.InputTuple,
      OrderPlacedEvent.OutputTuple,
      OrderPlacedEvent.OutputObject
    >;
    OrderPlaced: TypedContractEvent<
      OrderPlacedEvent.InputTuple,
      OrderPlacedEvent.OutputTuple,
      OrderPlacedEvent.OutputObject
    >;
  };
}
