/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPool {
  export type PoolConfigStruct = {
    token0: AddressLike;
    token1: AddressLike;
    poolType: BigNumberish;
    tickSpacing: BigNumberish;
    sigmoidAlpha: BigNumberish;
    sigmoidK: BigNumberish;
    baseFee: BigNumberish;
    maxImpactFee: BigNumberish;
  };

  export type PoolConfigStructOutput = [
    token0: string,
    token1: string,
    poolType: bigint,
    tickSpacing: bigint,
    sigmoidAlpha: bigint,
    sigmoidK: bigint,
    baseFee: bigint,
    maxImpactFee: bigint
  ] & {
    token0: string;
    token1: string;
    poolType: bigint;
    tickSpacing: bigint;
    sigmoidAlpha: bigint;
    sigmoidK: bigint;
    baseFee: bigint;
    maxImpactFee: bigint;
  };

  export type PoolStateStruct = {
    sqrtPriceX96: BigNumberish;
    currentTick: BigNumberish;
    liquidity: BigNumberish;
    reserve0: BigNumberish;
    reserve1: BigNumberish;
    feeGrowthGlobal0X128: BigNumberish;
    feeGrowthGlobal1X128: BigNumberish;
    protocolFees0: BigNumberish;
    protocolFees1: BigNumberish;
    lastObservationTimestamp: BigNumberish;
    initialized: boolean;
  };

  export type PoolStateStructOutput = [
    sqrtPriceX96: bigint,
    currentTick: bigint,
    liquidity: bigint,
    reserve0: bigint,
    reserve1: bigint,
    feeGrowthGlobal0X128: bigint,
    feeGrowthGlobal1X128: bigint,
    protocolFees0: bigint,
    protocolFees1: bigint,
    lastObservationTimestamp: bigint,
    initialized: boolean
  ] & {
    sqrtPriceX96: bigint;
    currentTick: bigint;
    liquidity: bigint;
    reserve0: bigint;
    reserve1: bigint;
    feeGrowthGlobal0X128: bigint;
    feeGrowthGlobal1X128: bigint;
    protocolFees0: bigint;
    protocolFees1: bigint;
    lastObservationTimestamp: bigint;
    initialized: boolean;
  };
}

export interface PoolFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "computePoolId"
      | "createPool"
      | "getAllPoolIds"
      | "getPoolConfig"
      | "getPoolCount"
      | "getPoolCreator"
      | "getPoolState"
      | "initializePool"
      | "pause"
      | "poolExists"
      | "setEventEmitter"
      | "setPauseGuardian"
      | "setTreasury"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PoolCreated" | "PoolInitialized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "computePoolId",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [IPool.PoolConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPoolIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolConfig",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolCreator",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializePool",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEventEmitter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPauseGuardian",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "computePoolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPoolIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEventEmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPauseGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    token0: AddressLike,
    token1: AddressLike,
    poolType: BigNumberish,
    tickSpacing: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    token0: string,
    token1: string,
    poolType: bigint,
    tickSpacing: bigint
  ];
  export interface OutputObject {
    poolId: string;
    token0: string;
    token1: string;
    poolType: bigint;
    tickSpacing: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolInitializedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sqrtPriceX96: BigNumberish,
    tick: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sqrtPriceX96: bigint,
    tick: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sqrtPriceX96: bigint;
    tick: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PoolFacet extends BaseContract {
  connect(runner?: ContractRunner | null): PoolFacet;
  waitForDeployment(): Promise<this>;

  interface: PoolFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computePoolId: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, tickSpacing: BigNumberish],
    [string],
    "view"
  >;

  createPool: TypedContractMethod<
    [config: IPool.PoolConfigStruct],
    [string],
    "nonpayable"
  >;

  getAllPoolIds: TypedContractMethod<[], [string[]], "view">;

  getPoolConfig: TypedContractMethod<
    [poolId: BytesLike],
    [IPool.PoolConfigStructOutput],
    "view"
  >;

  getPoolCount: TypedContractMethod<[], [bigint], "view">;

  getPoolCreator: TypedContractMethod<[poolId: BytesLike], [string], "view">;

  getPoolState: TypedContractMethod<
    [poolId: BytesLike],
    [IPool.PoolStateStructOutput],
    "view"
  >;

  initializePool: TypedContractMethod<
    [poolId: BytesLike, sqrtPriceX96: BigNumberish],
    [void],
    "nonpayable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  poolExists: TypedContractMethod<[poolId: BytesLike], [boolean], "view">;

  setEventEmitter: TypedContractMethod<
    [emitter: AddressLike],
    [void],
    "nonpayable"
  >;

  setPauseGuardian: TypedContractMethod<
    [guardian: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computePoolId"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, tickSpacing: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [config: IPool.PoolConfigStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllPoolIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPoolConfig"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [IPool.PoolConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolCreator"
  ): TypedContractMethod<[poolId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolState"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [IPool.PoolStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializePool"
  ): TypedContractMethod<
    [poolId: BytesLike, sqrtPriceX96: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "poolExists"
  ): TypedContractMethod<[poolId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setEventEmitter"
  ): TypedContractMethod<[emitter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPauseGuardian"
  ): TypedContractMethod<
    [guardian: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolInitialized"
  ): TypedContractEvent<
    PoolInitializedEvent.InputTuple,
    PoolInitializedEvent.OutputTuple,
    PoolInitializedEvent.OutputObject
  >;

  filters: {
    "PoolCreated(bytes32,address,address,uint8,uint24)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "PoolInitialized(bytes32,uint160,int24)": TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;
    PoolInitialized: TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;
  };
}
