/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ISwapFacet {
  export type SwapParamsStruct = {
    poolId: BytesLike;
    zeroForOne: boolean;
    amountSpecified: BigNumberish;
    sqrtPriceLimitX96: BigNumberish;
    recipient: AddressLike;
    deadline: BigNumberish;
  };

  export type SwapParamsStructOutput = [
    poolId: string,
    zeroForOne: boolean,
    amountSpecified: bigint,
    sqrtPriceLimitX96: bigint,
    recipient: string,
    deadline: bigint
  ] & {
    poolId: string;
    zeroForOne: boolean;
    amountSpecified: bigint;
    sqrtPriceLimitX96: bigint;
    recipient: string;
    deadline: bigint;
  };

  export type SwapResultStruct = {
    amount0: BigNumberish;
    amount1: BigNumberish;
    sqrtPriceX96After: BigNumberish;
    tickAfter: BigNumberish;
    liquidityAfter: BigNumberish;
    feeAmount: BigNumberish;
  };

  export type SwapResultStructOutput = [
    amount0: bigint,
    amount1: bigint,
    sqrtPriceX96After: bigint,
    tickAfter: bigint,
    liquidityAfter: bigint,
    feeAmount: bigint
  ] & {
    amount0: bigint;
    amount1: bigint;
    sqrtPriceX96After: bigint;
    tickAfter: bigint;
    liquidityAfter: bigint;
    feeAmount: bigint;
  };
}

export interface SwapFacetInterface extends Interface {
  getFunction(nameOrSignature: "swap"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Swap"): EventFragment;

  encodeFunctionData(
    functionFragment: "swap",
    values: [ISwapFacet.SwapParamsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
}

export namespace SwapEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    sqrtPriceX96: BigNumberish,
    liquidity: BigNumberish,
    tick: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sender: string,
    recipient: string,
    amount0: bigint,
    amount1: bigint,
    sqrtPriceX96: bigint,
    liquidity: bigint,
    tick: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sender: string;
    recipient: string;
    amount0: bigint;
    amount1: bigint;
    sqrtPriceX96: bigint;
    liquidity: bigint;
    tick: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwapFacet extends BaseContract {
  connect(runner?: ContractRunner | null): SwapFacet;
  waitForDeployment(): Promise<this>;

  interface: SwapFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  swap: TypedContractMethod<
    [params: ISwapFacet.SwapParamsStruct],
    [ISwapFacet.SwapResultStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [params: ISwapFacet.SwapParamsStruct],
    [ISwapFacet.SwapResultStructOutput],
    "nonpayable"
  >;

  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;

  filters: {
    "Swap(bytes32,address,address,int256,int256,uint160,uint128,int24,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
  };
}
