/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IOrderFacet {
  export type OrderStruct = {
    orderId: BigNumberish;
    poolId: BytesLike;
    owner: AddressLike;
    orderType: BigNumberish;
    zeroForOne: boolean;
    targetTick: BigNumberish;
    amountTotal: BigNumberish;
    amountFilled: BigNumberish;
    depositTimestamp: BigNumberish;
    expiry: BigNumberish;
    status: BigNumberish;
  };

  export type OrderStructOutput = [
    orderId: bigint,
    poolId: string,
    owner: string,
    orderType: bigint,
    zeroForOne: boolean,
    targetTick: bigint,
    amountTotal: bigint,
    amountFilled: bigint,
    depositTimestamp: bigint,
    expiry: bigint,
    status: bigint
  ] & {
    orderId: bigint;
    poolId: string;
    owner: string;
    orderType: bigint;
    zeroForOne: boolean;
    targetTick: bigint;
    amountTotal: bigint;
    amountFilled: bigint;
    depositTimestamp: bigint;
    expiry: bigint;
    status: bigint;
  };
}

export declare namespace OrderManager {
  export type PlaceLimitOrderParamsStruct = {
    poolId: BytesLike;
    zeroForOne: boolean;
    targetTick: BigNumberish;
    amount: BigNumberish;
    expiry: BigNumberish;
    deadline: BigNumberish;
  };

  export type PlaceLimitOrderParamsStructOutput = [
    poolId: string,
    zeroForOne: boolean,
    targetTick: bigint,
    amount: bigint,
    expiry: bigint,
    deadline: bigint
  ] & {
    poolId: string;
    zeroForOne: boolean;
    targetTick: bigint;
    amount: bigint;
    expiry: bigint;
    deadline: bigint;
  };

  export type PlaceStopOrderParamsStruct = {
    poolId: BytesLike;
    zeroForOne: boolean;
    targetTick: BigNumberish;
    amount: BigNumberish;
    expiry: BigNumberish;
    deadline: BigNumberish;
  };

  export type PlaceStopOrderParamsStructOutput = [
    poolId: string,
    zeroForOne: boolean,
    targetTick: bigint,
    amount: bigint,
    expiry: bigint,
    deadline: bigint
  ] & {
    poolId: string;
    zeroForOne: boolean;
    targetTick: bigint;
    amount: bigint;
    expiry: bigint;
    deadline: bigint;
  };
}

export interface OrderManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchExecuteOrders"
      | "cancelOrder"
      | "diamond"
      | "executeOrder"
      | "getActiveOrderCount"
      | "getOrder"
      | "getOrdersAtTick"
      | "placeLimitOrder"
      | "placeStopOrder"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LimitOrderPlaced" | "StopOrderPlaced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchExecuteOrders",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "diamond", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOrderCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrdersAtTick",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeLimitOrder",
    values: [OrderManager.PlaceLimitOrderParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "placeStopOrder",
    values: [OrderManager.PlaceStopOrderParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchExecuteOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "diamond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrdersAtTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placeLimitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placeStopOrder",
    data: BytesLike
  ): Result;
}

export namespace LimitOrderPlacedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    poolId: BytesLike,
    owner: AddressLike
  ];
  export type OutputTuple = [orderId: bigint, poolId: string, owner: string];
  export interface OutputObject {
    orderId: bigint;
    poolId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StopOrderPlacedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    poolId: BytesLike,
    owner: AddressLike
  ];
  export type OutputTuple = [orderId: bigint, poolId: string, owner: string];
  export interface OutputObject {
    orderId: bigint;
    poolId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OrderManager extends BaseContract {
  connect(runner?: ContractRunner | null): OrderManager;
  waitForDeployment(): Promise<this>;

  interface: OrderManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchExecuteOrders: TypedContractMethod<
    [orderIds: BigNumberish[]],
    [bigint],
    "nonpayable"
  >;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  diamond: TypedContractMethod<[], [string], "view">;

  executeOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [[bigint, bigint] & { amountOut: bigint; bounty: bigint }],
    "nonpayable"
  >;

  getActiveOrderCount: TypedContractMethod<
    [poolId: BytesLike],
    [bigint],
    "view"
  >;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [IOrderFacet.OrderStructOutput],
    "view"
  >;

  getOrdersAtTick: TypedContractMethod<
    [poolId: BytesLike, tick: BigNumberish],
    [bigint[]],
    "view"
  >;

  placeLimitOrder: TypedContractMethod<
    [params: OrderManager.PlaceLimitOrderParamsStruct],
    [bigint],
    "nonpayable"
  >;

  placeStopOrder: TypedContractMethod<
    [params: OrderManager.PlaceStopOrderParamsStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchExecuteOrders"
  ): TypedContractMethod<[orderIds: BigNumberish[]], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "diamond"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [[bigint, bigint] & { amountOut: bigint; bounty: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveOrderCount"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [IOrderFacet.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrdersAtTick"
  ): TypedContractMethod<
    [poolId: BytesLike, tick: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeLimitOrder"
  ): TypedContractMethod<
    [params: OrderManager.PlaceLimitOrderParamsStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "placeStopOrder"
  ): TypedContractMethod<
    [params: OrderManager.PlaceStopOrderParamsStruct],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "LimitOrderPlaced"
  ): TypedContractEvent<
    LimitOrderPlacedEvent.InputTuple,
    LimitOrderPlacedEvent.OutputTuple,
    LimitOrderPlacedEvent.OutputObject
  >;
  getEvent(
    key: "StopOrderPlaced"
  ): TypedContractEvent<
    StopOrderPlacedEvent.InputTuple,
    StopOrderPlacedEvent.OutputTuple,
    StopOrderPlacedEvent.OutputObject
  >;

  filters: {
    "LimitOrderPlaced(uint256,bytes32,address)": TypedContractEvent<
      LimitOrderPlacedEvent.InputTuple,
      LimitOrderPlacedEvent.OutputTuple,
      LimitOrderPlacedEvent.OutputObject
    >;
    LimitOrderPlaced: TypedContractEvent<
      LimitOrderPlacedEvent.InputTuple,
      LimitOrderPlacedEvent.OutputTuple,
      LimitOrderPlacedEvent.OutputObject
    >;

    "StopOrderPlaced(uint256,bytes32,address)": TypedContractEvent<
      StopOrderPlacedEvent.InputTuple,
      StopOrderPlacedEvent.OutputTuple,
      StopOrderPlacedEvent.OutputObject
    >;
    StopOrderPlaced: TypedContractEvent<
      StopOrderPlacedEvent.InputTuple,
      StopOrderPlacedEvent.OutputTuple,
      StopOrderPlacedEvent.OutputObject
    >;
  };
}
