/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface QuoterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "diamond"
      | "estimateFee"
      | "getPoolPrice"
      | "quoteExactInput"
      | "quoteExactInputSingle"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "diamond", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "estimateFee",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInput",
    values: [BytesLike[], boolean[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInputSingle",
    values: [BytesLike, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "diamond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "estimateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInputSingle",
    data: BytesLike
  ): Result;
}

export interface Quoter extends BaseContract {
  connect(runner?: ContractRunner | null): Quoter;
  waitForDeployment(): Promise<this>;

  interface: QuoterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  diamond: TypedContractMethod<[], [string], "view">;

  estimateFee: TypedContractMethod<
    [poolId: BytesLike, tradeSize: BigNumberish],
    [bigint],
    "view"
  >;

  getPoolPrice: TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        sqrtPriceX96: bigint;
        tick: bigint;
        liquidity: bigint;
      }
    ],
    "view"
  >;

  quoteExactInput: TypedContractMethod<
    [poolIds: BytesLike[], zeroForOnes: boolean[], amountIn: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  quoteExactInputSingle: TypedContractMethod<
    [poolId: BytesLike, zeroForOne: boolean, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        fee: bigint;
        sqrtPriceX96After: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "diamond"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "estimateFee"
  ): TypedContractMethod<
    [poolId: BytesLike, tradeSize: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolPrice"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        sqrtPriceX96: bigint;
        tick: bigint;
        liquidity: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteExactInput"
  ): TypedContractMethod<
    [poolIds: BytesLike[], zeroForOnes: boolean[], amountIn: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "quoteExactInputSingle"
  ): TypedContractMethod<
    [poolId: BytesLike, zeroForOne: boolean, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        fee: bigint;
        sqrtPriceX96After: bigint;
      }
    ],
    "nonpayable"
  >;

  filters: {};
}
