/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Router {
  export type ExactInputParamsStruct = {
    poolIds: BytesLike[];
    zeroForOnes: boolean[];
    tokenIn: AddressLike;
    amountIn: BigNumberish;
    amountOutMinimum: BigNumberish;
    recipient: AddressLike;
    deadline: BigNumberish;
  };

  export type ExactInputParamsStructOutput = [
    poolIds: string[],
    zeroForOnes: boolean[],
    tokenIn: string,
    amountIn: bigint,
    amountOutMinimum: bigint,
    recipient: string,
    deadline: bigint
  ] & {
    poolIds: string[];
    zeroForOnes: boolean[];
    tokenIn: string;
    amountIn: bigint;
    amountOutMinimum: bigint;
    recipient: string;
    deadline: bigint;
  };

  export type ExactInputSingleParamsStruct = {
    poolId: BytesLike;
    zeroForOne: boolean;
    amountIn: BigNumberish;
    amountOutMinimum: BigNumberish;
    sqrtPriceLimitX96: BigNumberish;
    recipient: AddressLike;
    deadline: BigNumberish;
  };

  export type ExactInputSingleParamsStructOutput = [
    poolId: string,
    zeroForOne: boolean,
    amountIn: bigint,
    amountOutMinimum: bigint,
    sqrtPriceLimitX96: bigint,
    recipient: string,
    deadline: bigint
  ] & {
    poolId: string;
    zeroForOne: boolean;
    amountIn: bigint;
    amountOutMinimum: bigint;
    sqrtPriceLimitX96: bigint;
    recipient: string;
    deadline: bigint;
  };

  export type ExactOutputSingleParamsStruct = {
    poolId: BytesLike;
    zeroForOne: boolean;
    amountOut: BigNumberish;
    amountInMaximum: BigNumberish;
    sqrtPriceLimitX96: BigNumberish;
    recipient: AddressLike;
    deadline: BigNumberish;
  };

  export type ExactOutputSingleParamsStructOutput = [
    poolId: string,
    zeroForOne: boolean,
    amountOut: bigint,
    amountInMaximum: bigint,
    sqrtPriceLimitX96: bigint,
    recipient: string,
    deadline: bigint
  ] & {
    poolId: string;
    zeroForOne: boolean;
    amountOut: bigint;
    amountInMaximum: bigint;
    sqrtPriceLimitX96: bigint;
    recipient: string;
    deadline: bigint;
  };
}

export interface RouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "diamond"
      | "exactInput"
      | "exactInputSingle"
      | "exactOutputSingle"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "diamond", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "exactInput",
    values: [Router.ExactInputParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "exactInputSingle",
    values: [Router.ExactInputSingleParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutputSingle",
    values: [Router.ExactOutputSingleParamsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "diamond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exactInput", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exactInputSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutputSingle",
    data: BytesLike
  ): Result;
}

export interface Router extends BaseContract {
  connect(runner?: ContractRunner | null): Router;
  waitForDeployment(): Promise<this>;

  interface: RouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  diamond: TypedContractMethod<[], [string], "view">;

  exactInput: TypedContractMethod<
    [params: Router.ExactInputParamsStruct],
    [bigint],
    "nonpayable"
  >;

  exactInputSingle: TypedContractMethod<
    [params: Router.ExactInputSingleParamsStruct],
    [bigint],
    "nonpayable"
  >;

  exactOutputSingle: TypedContractMethod<
    [params: Router.ExactOutputSingleParamsStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "diamond"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "exactInput"
  ): TypedContractMethod<
    [params: Router.ExactInputParamsStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exactInputSingle"
  ): TypedContractMethod<
    [params: Router.ExactInputSingleParamsStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exactOutputSingle"
  ): TypedContractMethod<
    [params: Router.ExactOutputSingleParamsStruct],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
