/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  LibOracle,
  LibOracleInterface,
} from "../../../core/libraries/LibOracle";

const _abi = [
  {
    inputs: [],
    name: "InsufficientObservationHistory",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidObservationPeriod",
    type: "error",
  },
  {
    inputs: [],
    name: "OracleNotInitialized",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212202f7db45fea64eee25351fc7adf860fd88465a2f7ea3200d2b1f57d5f71512ef664736f6c634300081b0033";

type LibOracleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibOracleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibOracle__factory extends ContractFactory {
  constructor(...args: LibOracleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LibOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LibOracle__factory {
    return super.connect(runner) as LibOracle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibOracleInterface {
    return new Interface(_abi) as LibOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): LibOracle {
    return new Contract(address, _abi, runner) as unknown as LibOracle;
  }
}
