/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  LibOrder,
  LibOrderInterface,
} from "../../../core/libraries/LibOrder";

const _abi = [
  {
    inputs: [],
    name: "InvalidExpiry",
    type: "error",
  },
  {
    inputs: [],
    name: "MaxOrdersExceeded",
    type: "error",
  },
  {
    inputs: [],
    name: "NotOrderOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "OrderAlreadyFilled",
    type: "error",
  },
  {
    inputs: [],
    name: "OrderDoesNotExist",
    type: "error",
  },
  {
    inputs: [],
    name: "OrderNotActive",
    type: "error",
  },
  {
    inputs: [],
    name: "OrderTooSmall",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220a180050ddf114808376d754a25fa9af5bf4ac496ba22edc55ae4f610ce31bcac64736f6c634300081b0033";

type LibOrderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibOrderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibOrder__factory extends ContractFactory {
  constructor(...args: LibOrderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LibOrder & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LibOrder__factory {
    return super.connect(runner) as LibOrder__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibOrderInterface {
    return new Interface(_abi) as LibOrderInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): LibOrder {
    return new Contract(address, _abi, runner) as unknown as LibOrder;
  }
}
