/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  LibPool,
  LibPoolInterface,
} from "../../../core/libraries/LibPool";

const _abi = [
  {
    inputs: [],
    name: "IdenticalTokens",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidTickSpacing",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidTokenOrder",
    type: "error",
  },
  {
    inputs: [],
    name: "PoolAlreadyExists",
    type: "error",
  },
  {
    inputs: [],
    name: "PoolDoesNotExist",
    type: "error",
  },
  {
    inputs: [],
    name: "PoolNotInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea264697066735822122095277a4f07bd7158251cb13220bbeeed462d6fa607ba78d9bd777a0f5491f25d64736f6c634300081b0033";

type LibPoolConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibPoolConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibPool__factory extends ContractFactory {
  constructor(...args: LibPoolConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LibPool & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LibPool__factory {
    return super.connect(runner) as LibPool__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibPoolInterface {
    return new Interface(_abi) as LibPoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): LibPool {
    return new Contract(address, _abi, runner) as unknown as LibPool;
  }
}
