/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  LibPosition,
  LibPositionInterface,
} from "../../../core/libraries/LibPosition";

const _abi = [
  {
    inputs: [],
    name: "InsufficientLiquidity",
    type: "error",
  },
  {
    inputs: [],
    name: "NotPositionOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "PositionDoesNotExist",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220ec4aefd36a2b5f668c8ef16898580ab4a1d8d5a99358aebadbf75e2050e257d364736f6c634300081b0033";

type LibPositionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibPositionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibPosition__factory extends ContractFactory {
  constructor(...args: LibPositionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LibPosition & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LibPosition__factory {
    return super.connect(runner) as LibPosition__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibPositionInterface {
    return new Interface(_abi) as LibPositionInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): LibPosition {
    return new Contract(address, _abi, runner) as unknown as LibPosition;
  }
}
