/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPositionDescriptor } from "./IPositionDescriptor";
export type { PositionManager } from "./PositionManager";
