/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoolReader,
  IPoolReaderInterface,
} from "../../../core/EventEmitter.sol/IPoolReader";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "getPoolState",
    outputs: [
      {
        components: [
          {
            internalType: "uint160",
            name: "sqrtPriceX96",
            type: "uint160",
          },
          {
            internalType: "int24",
            name: "currentTick",
            type: "int24",
          },
          {
            internalType: "uint128",
            name: "liquidity",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "reserve0",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "reserve1",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeGrowthGlobal0X128",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeGrowthGlobal1X128",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "protocolFees0",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "protocolFees1",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "lastObservationTimestamp",
            type: "uint32",
          },
          {
            internalType: "bool",
            name: "initialized",
            type: "bool",
          },
        ],
        internalType: "struct IPool.PoolState",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPoolReader__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolReaderInterface {
    return new Interface(_abi) as IPoolReaderInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPoolReader {
    return new Contract(address, _abi, runner) as unknown as IPoolReader;
  }
}
