/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace InitDiamond {
  export type InitArgsStruct = {
    treasury: AddressLike;
    flashLoanFeeBps: BigNumberish;
    maxOrdersPerPool: BigNumberish;
    defaultOrderTTL: BigNumberish;
    minOrderSize: BigNumberish;
    keeperBountyBps: BigNumberish;
    epochDuration: BigNumberish;
    minSwapsForRebate: BigNumberish;
    maxTradeSizeBps: BigNumberish;
  };

  export type InitArgsStructOutput = [
    treasury: string,
    flashLoanFeeBps: bigint,
    maxOrdersPerPool: bigint,
    defaultOrderTTL: bigint,
    minOrderSize: bigint,
    keeperBountyBps: bigint,
    epochDuration: bigint,
    minSwapsForRebate: bigint,
    maxTradeSizeBps: bigint
  ] & {
    treasury: string;
    flashLoanFeeBps: bigint;
    maxOrdersPerPool: bigint;
    defaultOrderTTL: bigint;
    minOrderSize: bigint;
    keeperBountyBps: bigint;
    epochDuration: bigint;
    minSwapsForRebate: bigint;
    maxTradeSizeBps: bigint;
  };
}

export interface InitDiamondInterface extends Interface {
  getFunction(nameOrSignature: "init"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "init",
    values: [InitDiamond.InitArgsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
}

export interface InitDiamond extends BaseContract {
  connect(runner?: ContractRunner | null): InitDiamond;
  waitForDeployment(): Promise<this>;

  interface: InitDiamondInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  init: TypedContractMethod<
    [args: InitDiamond.InitArgsStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "init"
  ): TypedContractMethod<
    [args: InitDiamond.InitArgsStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
