/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IASAMMOracle,
  IASAMMOracleInterface,
} from "../../../core/interfaces/IASAMMOracle";

const _abi = [
  {
    inputs: [],
    name: "spotPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "period",
        type: "uint32",
      },
    ],
    name: "twapPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IASAMMOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IASAMMOracleInterface {
    return new Interface(_abi) as IASAMMOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IASAMMOracle {
    return new Contract(address, _abi, runner) as unknown as IASAMMOracle;
  }
}
