/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeFacet,
  IFeeFacetInterface,
} from "../../../core/interfaces/IFeeFacet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "baseFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "maxImpactFee",
        type: "uint256",
      },
    ],
    name: "FeeConfigUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    name: "ProtocolFeesCollected",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "tradeSize",
        type: "uint256",
      },
    ],
    name: "calculateFee",
    outputs: [
      {
        internalType: "uint256",
        name: "feeBps",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "collectProtocolFees",
    outputs: [
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "getFeeConfig",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "baseFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxImpactFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lpShareBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "protocolShareBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "traderShareBps",
            type: "uint256",
          },
        ],
        internalType: "struct IFeeFacet.FeeConfig",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "baseFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxImpactFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lpShareBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "protocolShareBps",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "traderShareBps",
            type: "uint256",
          },
        ],
        internalType: "struct IFeeFacet.FeeConfig",
        name: "config",
        type: "tuple",
      },
    ],
    name: "setFeeConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeFacetInterface {
    return new Interface(_abi) as IFeeFacetInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFeeFacet {
    return new Contract(address, _abi, runner) as unknown as IFeeFacet;
  }
}
