/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRewardFacet,
  IRewardFacetInterface,
} from "../../../core/interfaces/IRewardFacet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalRebatePool0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalRebatePool1",
        type: "uint256",
      },
    ],
    name: "EpochAdvanced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "lp",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "positionId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    name: "LPRewardsClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "trader",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    name: "TraderRebateClaimed",
    type: "event",
  },
  {
    inputs: [],
    name: "advanceEpoch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "claimTraderRebate",
    outputs: [
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentEpoch",
    outputs: [
      {
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "positionId",
        type: "uint256",
      },
    ],
    name: "getLPMultiplier",
    outputs: [
      {
        internalType: "uint256",
        name: "multiplier",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "positionId",
        type: "uint256",
      },
    ],
    name: "getLPRewardInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "loyaltyMultiplier",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "accumulatedFees0",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "accumulatedFees1",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "depositTimestamp",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "cumulativeVolume",
            type: "uint256",
          },
        ],
        internalType: "struct IRewardFacet.LPRewardInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "trader",
        type: "address",
      },
    ],
    name: "getTraderRewardInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "currentEpoch",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "epochSwapCount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "epochVolume",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "pendingRebate0",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "pendingRebate1",
            type: "uint256",
          },
        ],
        internalType: "struct IRewardFacet.TraderRewardInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "epochDuration",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minSwapsForRebate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxTradeSize",
            type: "uint256",
          },
        ],
        internalType: "struct IRewardFacet.EpochConfig",
        name: "config",
        type: "tuple",
      },
    ],
    name: "setEpochConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRewardFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardFacetInterface {
    return new Interface(_abi) as IRewardFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRewardFacet {
    return new Contract(address, _abi, runner) as unknown as IRewardFacet;
  }
}
