/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace EventEmitter {
  export type PoolInfoStruct = {
    token0: AddressLike;
    token1: AddressLike;
    creator: AddressLike;
    tickSpacing: BigNumberish;
    createdAt: BigNumberish;
    totalSwaps: BigNumberish;
    totalVolume0: BigNumberish;
    totalVolume1: BigNumberish;
    lastSqrtPriceX96: BigNumberish;
    previousSqrtPriceX96: BigNumberish;
    lastTick: BigNumberish;
  };

  export type PoolInfoStructOutput = [
    token0: string,
    token1: string,
    creator: string,
    tickSpacing: bigint,
    createdAt: bigint,
    totalSwaps: bigint,
    totalVolume0: bigint,
    totalVolume1: bigint,
    lastSqrtPriceX96: bigint,
    previousSqrtPriceX96: bigint,
    lastTick: bigint
  ] & {
    token0: string;
    token1: string;
    creator: string;
    tickSpacing: bigint;
    createdAt: bigint;
    totalSwaps: bigint;
    totalVolume0: bigint;
    totalVolume1: bigint;
    lastSqrtPriceX96: bigint;
    previousSqrtPriceX96: bigint;
    lastTick: bigint;
  };
}

export interface EventEmitterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allPoolIds"
      | "diamond"
      | "emitFeesCollected"
      | "emitLiquidityAdded"
      | "emitLiquidityRemoved"
      | "emitPoolCreated"
      | "emitPoolInitialized"
      | "emitPoolSnapshot"
      | "emitSwap"
      | "getAllPoolIds"
      | "getMultiPoolStats"
      | "getPoolCount"
      | "getPoolInfo"
      | "getPoolLPCount"
      | "getPoolLPs"
      | "getPoolStats"
      | "getPrice"
      | "getPriceChange"
      | "getReserves"
      | "isPoolLP"
      | "isRegistered"
      | "owner"
      | "poolInfos"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesCollectedDetailed"
      | "LiquidityAddedDetailed"
      | "LiquidityRemovedDetailed"
      | "PoolCreatedDetailed"
      | "PoolInitializedDetailed"
      | "PoolSnapshot"
      | "SwapExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allPoolIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "diamond", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emitFeesCollected",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emitLiquidityAdded",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emitLiquidityRemoved",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emitPoolCreated",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emitPoolInitialized",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitPoolSnapshot",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emitSwap",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPoolIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMultiPoolStats",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolLPCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolLPs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolStats",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPriceChange",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPoolLP",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolInfos",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "allPoolIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "diamond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emitFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitLiquidityAdded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitLiquidityRemoved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitPoolCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitPoolInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitPoolSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "emitSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPoolIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultiPoolStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolLPCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPoolLPs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPoolLP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolInfos", data: BytesLike): Result;
}

export namespace FeesCollectedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    collector: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    protocolFees0Remaining: BigNumberish,
    protocolFees1Remaining: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    collector: string,
    amount0: bigint,
    amount1: bigint,
    protocolFees0Remaining: bigint,
    protocolFees1Remaining: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    collector: string;
    amount0: bigint;
    amount1: bigint;
    protocolFees0Remaining: bigint;
    protocolFees1Remaining: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    provider: AddressLike,
    positionId: BigNumberish,
    tickLower: BigNumberish,
    tickUpper: BigNumberish,
    liquidity: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish,
    reserve0After: BigNumberish,
    reserve1After: BigNumberish,
    totalLiquidityAfter: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    provider: string,
    positionId: bigint,
    tickLower: bigint,
    tickUpper: bigint,
    liquidity: bigint,
    amount0: bigint,
    amount1: bigint,
    reserve0After: bigint,
    reserve1After: bigint,
    totalLiquidityAfter: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    provider: string;
    positionId: bigint;
    tickLower: bigint;
    tickUpper: bigint;
    liquidity: bigint;
    amount0: bigint;
    amount1: bigint;
    reserve0After: bigint;
    reserve1After: bigint;
    totalLiquidityAfter: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    provider: AddressLike,
    positionId: BigNumberish,
    liquidityRemoved: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish,
    reserve0After: BigNumberish,
    reserve1After: BigNumberish,
    totalLiquidityAfter: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    provider: string,
    positionId: bigint,
    liquidityRemoved: bigint,
    amount0: bigint,
    amount1: bigint,
    reserve0After: bigint,
    reserve1After: bigint,
    totalLiquidityAfter: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    provider: string;
    positionId: bigint;
    liquidityRemoved: bigint;
    amount0: bigint;
    amount1: bigint;
    reserve0After: bigint;
    reserve1After: bigint;
    totalLiquidityAfter: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    creator: AddressLike,
    token0: AddressLike,
    token1: AddressLike,
    tickSpacing: BigNumberish,
    poolType: BigNumberish,
    baseFee: BigNumberish,
    maxImpactFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    creator: string,
    token0: string,
    token1: string,
    tickSpacing: bigint,
    poolType: bigint,
    baseFee: bigint,
    maxImpactFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    creator: string;
    token0: string;
    token1: string;
    tickSpacing: bigint;
    poolType: bigint;
    baseFee: bigint;
    maxImpactFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolInitializedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sqrtPriceX96: BigNumberish,
    tick: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sqrtPriceX96: bigint,
    tick: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sqrtPriceX96: bigint;
    tick: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolSnapshotEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sqrtPriceX96: BigNumberish,
    currentTick: BigNumberish,
    liquidity: BigNumberish,
    reserve0: BigNumberish,
    reserve1: BigNumberish,
    feeGrowthGlobal0X128: BigNumberish,
    feeGrowthGlobal1X128: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sqrtPriceX96: bigint,
    currentTick: bigint,
    liquidity: bigint,
    reserve0: bigint,
    reserve1: bigint,
    feeGrowthGlobal0X128: bigint,
    feeGrowthGlobal1X128: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sqrtPriceX96: bigint;
    currentTick: bigint;
    liquidity: bigint;
    reserve0: bigint;
    reserve1: bigint;
    feeGrowthGlobal0X128: bigint;
    feeGrowthGlobal1X128: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    zeroForOne: boolean,
    amount0: BigNumberish,
    amount1: BigNumberish,
    sqrtPriceX96Before: BigNumberish,
    sqrtPriceX96After: BigNumberish,
    tickBefore: BigNumberish,
    tickAfter: BigNumberish,
    liquidity: BigNumberish,
    feeAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sender: string,
    recipient: string,
    zeroForOne: boolean,
    amount0: bigint,
    amount1: bigint,
    sqrtPriceX96Before: bigint,
    sqrtPriceX96After: bigint,
    tickBefore: bigint,
    tickAfter: bigint,
    liquidity: bigint,
    feeAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sender: string;
    recipient: string;
    zeroForOne: boolean;
    amount0: bigint;
    amount1: bigint;
    sqrtPriceX96Before: bigint;
    sqrtPriceX96After: bigint;
    tickBefore: bigint;
    tickAfter: bigint;
    liquidity: bigint;
    feeAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventEmitter extends BaseContract {
  connect(runner?: ContractRunner | null): EventEmitter;
  waitForDeployment(): Promise<this>;

  interface: EventEmitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allPoolIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  diamond: TypedContractMethod<[], [string], "view">;

  emitFeesCollected: TypedContractMethod<
    [
      poolId: BytesLike,
      collector: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish,
      protocolFees0Remaining: BigNumberish,
      protocolFees1Remaining: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emitLiquidityAdded: TypedContractMethod<
    [
      poolId: BytesLike,
      provider: AddressLike,
      positionId: BigNumberish,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidity: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      reserve0After: BigNumberish,
      reserve1After: BigNumberish,
      totalLiquidityAfter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emitLiquidityRemoved: TypedContractMethod<
    [
      poolId: BytesLike,
      provider: AddressLike,
      positionId: BigNumberish,
      liquidityRemoved: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      reserve0After: BigNumberish,
      reserve1After: BigNumberish,
      totalLiquidityAfter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emitPoolCreated: TypedContractMethod<
    [
      poolId: BytesLike,
      creator: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      tickSpacing: BigNumberish,
      poolType: BigNumberish,
      baseFee: BigNumberish,
      maxImpactFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emitPoolInitialized: TypedContractMethod<
    [poolId: BytesLike, sqrtPriceX96: BigNumberish, tick: BigNumberish],
    [void],
    "nonpayable"
  >;

  emitPoolSnapshot: TypedContractMethod<
    [
      poolId: BytesLike,
      sqrtPriceX96: BigNumberish,
      currentTick: BigNumberish,
      liquidity: BigNumberish,
      reserve0: BigNumberish,
      reserve1: BigNumberish,
      feeGrowthGlobal0X128: BigNumberish,
      feeGrowthGlobal1X128: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emitSwap: TypedContractMethod<
    [
      poolId: BytesLike,
      sender: AddressLike,
      recipient: AddressLike,
      zeroForOne: boolean,
      amount0: BigNumberish,
      amount1: BigNumberish,
      sqrtPriceX96Before: BigNumberish,
      sqrtPriceX96After: BigNumberish,
      tickBefore: BigNumberish,
      tickAfter: BigNumberish,
      liquidity: BigNumberish,
      feeAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAllPoolIds: TypedContractMethod<[], [string[]], "view">;

  getMultiPoolStats: TypedContractMethod<
    [poolIds: BytesLike[]],
    [
      [bigint[], bigint[], bigint[], bigint[]] & {
        swapCounts: bigint[];
        volumes0: bigint[];
        volumes1: bigint[];
        prices: bigint[];
      }
    ],
    "view"
  >;

  getPoolCount: TypedContractMethod<[], [bigint], "view">;

  getPoolInfo: TypedContractMethod<
    [poolId: BytesLike],
    [EventEmitter.PoolInfoStructOutput],
    "view"
  >;

  getPoolLPCount: TypedContractMethod<[poolId: BytesLike], [bigint], "view">;

  getPoolLPs: TypedContractMethod<[poolId: BytesLike], [string[]], "view">;

  getPoolStats: TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        totalSwaps: bigint;
        totalVolume0: bigint;
        totalVolume1: bigint;
        lpCount: bigint;
        createdAt: bigint;
        creator: string;
      }
    ],
    "view"
  >;

  getPrice: TypedContractMethod<
    [poolId: BytesLike],
    [[bigint, bigint] & { sqrtPriceX96: bigint; tick: bigint }],
    "view"
  >;

  getPriceChange: TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        currentPrice: bigint;
        previousPrice: bigint;
        priceChangeBps: bigint;
      }
    ],
    "view"
  >;

  getReserves: TypedContractMethod<
    [poolId: BytesLike],
    [[bigint, bigint] & { reserve0: bigint; reserve1: bigint }],
    "view"
  >;

  isPoolLP: TypedContractMethod<
    [poolId: BytesLike, addr: AddressLike],
    [boolean],
    "view"
  >;

  isRegistered: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poolInfos: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        token0: string;
        token1: string;
        creator: string;
        tickSpacing: bigint;
        createdAt: bigint;
        totalSwaps: bigint;
        totalVolume0: bigint;
        totalVolume1: bigint;
        lastSqrtPriceX96: bigint;
        previousSqrtPriceX96: bigint;
        lastTick: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allPoolIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "diamond"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emitFeesCollected"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      collector: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish,
      protocolFees0Remaining: BigNumberish,
      protocolFees1Remaining: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitLiquidityAdded"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      provider: AddressLike,
      positionId: BigNumberish,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidity: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      reserve0After: BigNumberish,
      reserve1After: BigNumberish,
      totalLiquidityAfter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitLiquidityRemoved"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      provider: AddressLike,
      positionId: BigNumberish,
      liquidityRemoved: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      reserve0After: BigNumberish,
      reserve1After: BigNumberish,
      totalLiquidityAfter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitPoolCreated"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      creator: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      tickSpacing: BigNumberish,
      poolType: BigNumberish,
      baseFee: BigNumberish,
      maxImpactFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitPoolInitialized"
  ): TypedContractMethod<
    [poolId: BytesLike, sqrtPriceX96: BigNumberish, tick: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitPoolSnapshot"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      sqrtPriceX96: BigNumberish,
      currentTick: BigNumberish,
      liquidity: BigNumberish,
      reserve0: BigNumberish,
      reserve1: BigNumberish,
      feeGrowthGlobal0X128: BigNumberish,
      feeGrowthGlobal1X128: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitSwap"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      sender: AddressLike,
      recipient: AddressLike,
      zeroForOne: boolean,
      amount0: BigNumberish,
      amount1: BigNumberish,
      sqrtPriceX96Before: BigNumberish,
      sqrtPriceX96After: BigNumberish,
      tickBefore: BigNumberish,
      tickAfter: BigNumberish,
      liquidity: BigNumberish,
      feeAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllPoolIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMultiPoolStats"
  ): TypedContractMethod<
    [poolIds: BytesLike[]],
    [
      [bigint[], bigint[], bigint[], bigint[]] & {
        swapCounts: bigint[];
        volumes0: bigint[];
        volumes1: bigint[];
        prices: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [EventEmitter.PoolInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolLPCount"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolLPs"
  ): TypedContractMethod<[poolId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPoolStats"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        totalSwaps: bigint;
        totalVolume0: bigint;
        totalVolume1: bigint;
        lpCount: bigint;
        createdAt: bigint;
        creator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [[bigint, bigint] & { sqrtPriceX96: bigint; tick: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceChange"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        currentPrice: bigint;
        previousPrice: bigint;
        priceChangeBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [[bigint, bigint] & { reserve0: bigint; reserve1: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPoolLP"
  ): TypedContractMethod<
    [poolId: BytesLike, addr: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolInfos"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        token0: string;
        token1: string;
        creator: string;
        tickSpacing: bigint;
        createdAt: bigint;
        totalSwaps: bigint;
        totalVolume0: bigint;
        totalVolume1: bigint;
        lastSqrtPriceX96: bigint;
        previousSqrtPriceX96: bigint;
        lastTick: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "FeesCollectedDetailed"
  ): TypedContractEvent<
    FeesCollectedDetailedEvent.InputTuple,
    FeesCollectedDetailedEvent.OutputTuple,
    FeesCollectedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAddedDetailed"
  ): TypedContractEvent<
    LiquidityAddedDetailedEvent.InputTuple,
    LiquidityAddedDetailedEvent.OutputTuple,
    LiquidityAddedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemovedDetailed"
  ): TypedContractEvent<
    LiquidityRemovedDetailedEvent.InputTuple,
    LiquidityRemovedDetailedEvent.OutputTuple,
    LiquidityRemovedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreatedDetailed"
  ): TypedContractEvent<
    PoolCreatedDetailedEvent.InputTuple,
    PoolCreatedDetailedEvent.OutputTuple,
    PoolCreatedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "PoolInitializedDetailed"
  ): TypedContractEvent<
    PoolInitializedDetailedEvent.InputTuple,
    PoolInitializedDetailedEvent.OutputTuple,
    PoolInitializedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "PoolSnapshot"
  ): TypedContractEvent<
    PoolSnapshotEvent.InputTuple,
    PoolSnapshotEvent.OutputTuple,
    PoolSnapshotEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;

  filters: {
    "FeesCollectedDetailed(bytes32,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FeesCollectedDetailedEvent.InputTuple,
      FeesCollectedDetailedEvent.OutputTuple,
      FeesCollectedDetailedEvent.OutputObject
    >;
    FeesCollectedDetailed: TypedContractEvent<
      FeesCollectedDetailedEvent.InputTuple,
      FeesCollectedDetailedEvent.OutputTuple,
      FeesCollectedDetailedEvent.OutputObject
    >;

    "LiquidityAddedDetailed(bytes32,address,uint256,int24,int24,uint128,uint256,uint256,uint256,uint256,uint128,uint256)": TypedContractEvent<
      LiquidityAddedDetailedEvent.InputTuple,
      LiquidityAddedDetailedEvent.OutputTuple,
      LiquidityAddedDetailedEvent.OutputObject
    >;
    LiquidityAddedDetailed: TypedContractEvent<
      LiquidityAddedDetailedEvent.InputTuple,
      LiquidityAddedDetailedEvent.OutputTuple,
      LiquidityAddedDetailedEvent.OutputObject
    >;

    "LiquidityRemovedDetailed(bytes32,address,uint256,uint128,uint256,uint256,uint256,uint256,uint128,uint256)": TypedContractEvent<
      LiquidityRemovedDetailedEvent.InputTuple,
      LiquidityRemovedDetailedEvent.OutputTuple,
      LiquidityRemovedDetailedEvent.OutputObject
    >;
    LiquidityRemovedDetailed: TypedContractEvent<
      LiquidityRemovedDetailedEvent.InputTuple,
      LiquidityRemovedDetailedEvent.OutputTuple,
      LiquidityRemovedDetailedEvent.OutputObject
    >;

    "PoolCreatedDetailed(bytes32,address,address,address,uint24,uint8,uint256,uint256,uint256)": TypedContractEvent<
      PoolCreatedDetailedEvent.InputTuple,
      PoolCreatedDetailedEvent.OutputTuple,
      PoolCreatedDetailedEvent.OutputObject
    >;
    PoolCreatedDetailed: TypedContractEvent<
      PoolCreatedDetailedEvent.InputTuple,
      PoolCreatedDetailedEvent.OutputTuple,
      PoolCreatedDetailedEvent.OutputObject
    >;

    "PoolInitializedDetailed(bytes32,uint160,int24,uint256)": TypedContractEvent<
      PoolInitializedDetailedEvent.InputTuple,
      PoolInitializedDetailedEvent.OutputTuple,
      PoolInitializedDetailedEvent.OutputObject
    >;
    PoolInitializedDetailed: TypedContractEvent<
      PoolInitializedDetailedEvent.InputTuple,
      PoolInitializedDetailedEvent.OutputTuple,
      PoolInitializedDetailedEvent.OutputObject
    >;

    "PoolSnapshot(bytes32,uint160,int24,uint128,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      PoolSnapshotEvent.InputTuple,
      PoolSnapshotEvent.OutputTuple,
      PoolSnapshotEvent.OutputObject
    >;
    PoolSnapshot: TypedContractEvent<
      PoolSnapshotEvent.InputTuple,
      PoolSnapshotEvent.OutputTuple,
      PoolSnapshotEvent.OutputObject
    >;

    "SwapExecuted(bytes32,address,address,bool,int256,int256,uint160,uint160,int24,int24,uint128,uint256,uint256)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
  };
}
