/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface IEventEmitterInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "FeesCollectedDetailed"
      | "LiquidityAddedDetailed"
      | "LiquidityRemovedDetailed"
      | "PoolCreatedDetailed"
      | "PoolInitializedDetailed"
      | "PoolSnapshot"
      | "SwapExecuted"
  ): EventFragment;
}

export namespace FeesCollectedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    collector: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    protocolFees0Remaining: BigNumberish,
    protocolFees1Remaining: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    collector: string,
    amount0: bigint,
    amount1: bigint,
    protocolFees0Remaining: bigint,
    protocolFees1Remaining: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    collector: string;
    amount0: bigint;
    amount1: bigint;
    protocolFees0Remaining: bigint;
    protocolFees1Remaining: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    provider: AddressLike,
    positionId: BigNumberish,
    tickLower: BigNumberish,
    tickUpper: BigNumberish,
    liquidity: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish,
    reserve0After: BigNumberish,
    reserve1After: BigNumberish,
    totalLiquidityAfter: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    provider: string,
    positionId: bigint,
    tickLower: bigint,
    tickUpper: bigint,
    liquidity: bigint,
    amount0: bigint,
    amount1: bigint,
    reserve0After: bigint,
    reserve1After: bigint,
    totalLiquidityAfter: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    provider: string;
    positionId: bigint;
    tickLower: bigint;
    tickUpper: bigint;
    liquidity: bigint;
    amount0: bigint;
    amount1: bigint;
    reserve0After: bigint;
    reserve1After: bigint;
    totalLiquidityAfter: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    provider: AddressLike,
    positionId: BigNumberish,
    liquidityRemoved: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish,
    reserve0After: BigNumberish,
    reserve1After: BigNumberish,
    totalLiquidityAfter: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    provider: string,
    positionId: bigint,
    liquidityRemoved: bigint,
    amount0: bigint,
    amount1: bigint,
    reserve0After: bigint,
    reserve1After: bigint,
    totalLiquidityAfter: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    provider: string;
    positionId: bigint;
    liquidityRemoved: bigint;
    amount0: bigint;
    amount1: bigint;
    reserve0After: bigint;
    reserve1After: bigint;
    totalLiquidityAfter: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    creator: AddressLike,
    token0: AddressLike,
    token1: AddressLike,
    tickSpacing: BigNumberish,
    poolType: BigNumberish,
    baseFee: BigNumberish,
    maxImpactFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    creator: string,
    token0: string,
    token1: string,
    tickSpacing: bigint,
    poolType: bigint,
    baseFee: bigint,
    maxImpactFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    creator: string;
    token0: string;
    token1: string;
    tickSpacing: bigint;
    poolType: bigint;
    baseFee: bigint;
    maxImpactFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolInitializedDetailedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sqrtPriceX96: BigNumberish,
    tick: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sqrtPriceX96: bigint,
    tick: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sqrtPriceX96: bigint;
    tick: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolSnapshotEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sqrtPriceX96: BigNumberish,
    currentTick: BigNumberish,
    liquidity: BigNumberish,
    reserve0: BigNumberish,
    reserve1: BigNumberish,
    feeGrowthGlobal0X128: BigNumberish,
    feeGrowthGlobal1X128: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sqrtPriceX96: bigint,
    currentTick: bigint,
    liquidity: bigint,
    reserve0: bigint,
    reserve1: bigint,
    feeGrowthGlobal0X128: bigint,
    feeGrowthGlobal1X128: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sqrtPriceX96: bigint;
    currentTick: bigint;
    liquidity: bigint;
    reserve0: bigint;
    reserve1: bigint;
    feeGrowthGlobal0X128: bigint;
    feeGrowthGlobal1X128: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    zeroForOne: boolean,
    amount0: BigNumberish,
    amount1: BigNumberish,
    sqrtPriceX96Before: BigNumberish,
    sqrtPriceX96After: BigNumberish,
    tickBefore: BigNumberish,
    tickAfter: BigNumberish,
    liquidity: BigNumberish,
    feeAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sender: string,
    recipient: string,
    zeroForOne: boolean,
    amount0: bigint,
    amount1: bigint,
    sqrtPriceX96Before: bigint,
    sqrtPriceX96After: bigint,
    tickBefore: bigint,
    tickAfter: bigint,
    liquidity: bigint,
    feeAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sender: string;
    recipient: string;
    zeroForOne: boolean;
    amount0: bigint;
    amount1: bigint;
    sqrtPriceX96Before: bigint;
    sqrtPriceX96After: bigint;
    tickBefore: bigint;
    tickAfter: bigint;
    liquidity: bigint;
    feeAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEventEmitter extends BaseContract {
  connect(runner?: ContractRunner | null): IEventEmitter;
  waitForDeployment(): Promise<this>;

  interface: IEventEmitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "FeesCollectedDetailed"
  ): TypedContractEvent<
    FeesCollectedDetailedEvent.InputTuple,
    FeesCollectedDetailedEvent.OutputTuple,
    FeesCollectedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAddedDetailed"
  ): TypedContractEvent<
    LiquidityAddedDetailedEvent.InputTuple,
    LiquidityAddedDetailedEvent.OutputTuple,
    LiquidityAddedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemovedDetailed"
  ): TypedContractEvent<
    LiquidityRemovedDetailedEvent.InputTuple,
    LiquidityRemovedDetailedEvent.OutputTuple,
    LiquidityRemovedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreatedDetailed"
  ): TypedContractEvent<
    PoolCreatedDetailedEvent.InputTuple,
    PoolCreatedDetailedEvent.OutputTuple,
    PoolCreatedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "PoolInitializedDetailed"
  ): TypedContractEvent<
    PoolInitializedDetailedEvent.InputTuple,
    PoolInitializedDetailedEvent.OutputTuple,
    PoolInitializedDetailedEvent.OutputObject
  >;
  getEvent(
    key: "PoolSnapshot"
  ): TypedContractEvent<
    PoolSnapshotEvent.InputTuple,
    PoolSnapshotEvent.OutputTuple,
    PoolSnapshotEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;

  filters: {
    "FeesCollectedDetailed(bytes32,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FeesCollectedDetailedEvent.InputTuple,
      FeesCollectedDetailedEvent.OutputTuple,
      FeesCollectedDetailedEvent.OutputObject
    >;
    FeesCollectedDetailed: TypedContractEvent<
      FeesCollectedDetailedEvent.InputTuple,
      FeesCollectedDetailedEvent.OutputTuple,
      FeesCollectedDetailedEvent.OutputObject
    >;

    "LiquidityAddedDetailed(bytes32,address,uint256,int24,int24,uint128,uint256,uint256,uint256,uint256,uint128,uint256)": TypedContractEvent<
      LiquidityAddedDetailedEvent.InputTuple,
      LiquidityAddedDetailedEvent.OutputTuple,
      LiquidityAddedDetailedEvent.OutputObject
    >;
    LiquidityAddedDetailed: TypedContractEvent<
      LiquidityAddedDetailedEvent.InputTuple,
      LiquidityAddedDetailedEvent.OutputTuple,
      LiquidityAddedDetailedEvent.OutputObject
    >;

    "LiquidityRemovedDetailed(bytes32,address,uint256,uint128,uint256,uint256,uint256,uint256,uint128,uint256)": TypedContractEvent<
      LiquidityRemovedDetailedEvent.InputTuple,
      LiquidityRemovedDetailedEvent.OutputTuple,
      LiquidityRemovedDetailedEvent.OutputObject
    >;
    LiquidityRemovedDetailed: TypedContractEvent<
      LiquidityRemovedDetailedEvent.InputTuple,
      LiquidityRemovedDetailedEvent.OutputTuple,
      LiquidityRemovedDetailedEvent.OutputObject
    >;

    "PoolCreatedDetailed(bytes32,address,address,address,uint24,uint8,uint256,uint256,uint256)": TypedContractEvent<
      PoolCreatedDetailedEvent.InputTuple,
      PoolCreatedDetailedEvent.OutputTuple,
      PoolCreatedDetailedEvent.OutputObject
    >;
    PoolCreatedDetailed: TypedContractEvent<
      PoolCreatedDetailedEvent.InputTuple,
      PoolCreatedDetailedEvent.OutputTuple,
      PoolCreatedDetailedEvent.OutputObject
    >;

    "PoolInitializedDetailed(bytes32,uint160,int24,uint256)": TypedContractEvent<
      PoolInitializedDetailedEvent.InputTuple,
      PoolInitializedDetailedEvent.OutputTuple,
      PoolInitializedDetailedEvent.OutputObject
    >;
    PoolInitializedDetailed: TypedContractEvent<
      PoolInitializedDetailedEvent.InputTuple,
      PoolInitializedDetailedEvent.OutputTuple,
      PoolInitializedDetailedEvent.OutputObject
    >;

    "PoolSnapshot(bytes32,uint160,int24,uint128,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      PoolSnapshotEvent.InputTuple,
      PoolSnapshotEvent.OutputTuple,
      PoolSnapshotEvent.OutputObject
    >;
    PoolSnapshot: TypedContractEvent<
      PoolSnapshotEvent.InputTuple,
      PoolSnapshotEvent.OutputTuple,
      PoolSnapshotEvent.OutputObject
    >;

    "SwapExecuted(bytes32,address,address,bool,int256,int256,uint160,uint160,int24,int24,uint128,uint256,uint256)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
  };
}
