/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  FullMathTest,
  FullMathTestInterface,
} from "../../test/FullMathTest";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "denominator",
        type: "uint256",
      },
    ],
    name: "mulDiv",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
    ],
    name: "mulDivQ128",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "denominator",
        type: "uint256",
      },
    ],
    name: "mulDivRoundingUp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346015576103ab908161001b8239f35b600080fdfe6080604052600436101561001257600080fd5b60003560e01c80630af8b27f1461008457806392041d10146100635763aa9a09121461003d57600080fd5b3461005e57602061005661005036610142565b916101fc565b604051908152f35b600080fd5b3461005e57604036600319011261005e57602061005660243560043561016f565b3461005e5761009236610142565b9061009e8282856101fc565b92821561012c57096100b6575b602090604051908152f35b6000198110156100e75760001981146100d1576001016100ab565b634e487b7160e01b600052601160045260246000fd5b60405162461bcd60e51b815260206004820152601960248201527f46756c6c4d6174683a20726573756c74206f766572666c6f77000000000000006044820152606490fd5b634e487b7160e01b600052601260045260246000fd5b606090600319011261005e57600435906024359060443590565b818102929181159184041417156100d157565b6000929091600019818409920290818084109303918383146101f257505003600160801b11156101ad57634e487b7160e01b81526011600452602490fd5b60405162461bcd60e51b815260206004820152601e60248201527f46756c6c4d6174683a2064656e6f6d696e61746f72203c3d2070726f643100006044820152606490fd5b60801c9350915050565b91600019828409928281029283808610950394808603951461032257848311156101ad57829109816100d1576102498260000383168093049460018480600003040190858411900361015c565b92030417816003026003810483036100d157600218610268818461015c565b600203600281116100d15761027c9161015c565b610286818461015c565b600203600281116100d15761029a9161015c565b6102a4818461015c565b600203600281116100d1576102b89161015c565b6102c2818461015c565b600203600281116100d1576102d69161015c565b6102e0818461015c565b60020390600282116100d157610300916102f99161015c565b809361015c565b60020391600283116100d15761031f926103199161015c565b9061015c565b90565b505080925015610330570490565b60405162461bcd60e51b815260206004820152601a60248201527f46756c6c4d6174683a206469766973696f6e206279207a65726f0000000000006044820152606490fdfea2646970667358221220439f92a4120da320da0390763c3dab409e3f8c7495614a6120408be6a7b5eec264736f6c634300081b0033";

type FullMathTestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FullMathTestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FullMathTest__factory extends ContractFactory {
  constructor(...args: FullMathTestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FullMathTest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): FullMathTest__factory {
    return super.connect(runner) as FullMathTest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FullMathTestInterface {
    return new Interface(_abi) as FullMathTestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FullMathTest {
    return new Contract(address, _abi, runner) as unknown as FullMathTest;
  }
}
