/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPositionDescriptor__factory } from "./IPositionDescriptor__factory";
export { PositionManager__factory } from "./PositionManager__factory";
