/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPositionDescriptor,
  IPositionDescriptorInterface,
} from "../../../periphery/PositionManager.sol/IPositionDescriptor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "positionManager",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPositionDescriptor__factory {
  static readonly abi = _abi;
  static createInterface(): IPositionDescriptorInterface {
    return new Interface(_abi) as IPositionDescriptorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPositionDescriptor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPositionDescriptor;
  }
}
